name: CI

on:
  push:
    branches:
      - "main"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  PRERELASE: true

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Dry run tag
        id: tagDR
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          PRERELEASE: ${{ PRERELESE }}
          DRY_RUN: true

      - name: echo tag
        run: |
          echo "Running build for ${{ steps.tagDR.outputs.tag }} -> ${{ steps.tagDR.outputs.new_tag }} "

      # - 
    
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ${{ env.REGISTRY }}
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
          
      # - name: CMS - Build and push
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: ./database
      #     push: true
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/atlas-kompetencji:latest
